# Special hydra param, inherit defaults
defaults:
  - _self_

# Overrides for the env config
env:
  vehicles_count: 20
  target_speed: &target_speed 30
  duration: 6
  mc_horizon: 5
  n_montecarlo: 20
#  mc_period: 5
#==============
seed: 8675309
world_draws: 10

# Params for world sampling
params:
  - name: vehicles_density
    sampler:
      _target_: pymc.Uniform
      _args_:
        - vehicles_density
        - 0.5
        - 2.0
  - name: duration  # Just for testing
    fixed_value: 40

policy:
  model: "ProfitMaximizingPolicy"
loss:
  model: "LossModel"
  alpha: 10
  target_speed: *target_speed
  beta: 1
  scale: 0.1
preference_prior:
  model: "ExponentialPreferencePrior"
  p_star: 0.5
risk:
  model: "MonteCarloRiskModel"
