# Special hydra param, inherit defaults
defaults:
  - env: highway
  - _self_

# highway-env overrides
env_overrides:
  controlled_vehicles: 1
  duration: 40
  vehicles_count: 10
  lanes_count: 6
  vehicles_density: 1
  other_vehicles_type: highway_env.vehicle.behavior.IDMVehicle
  target_speed: &target_speed 12
#==============
seed: 8675309
world_draws: 8
#plan_duration: 20
#mc_horizon: 10
#n_montecarlo: 10

# Params for world sampling
params:
  - name: vehicles_density
    sampler:
      _target_: pymc.Uniform
      _args_:
        - vehicles_density
        - 0.5
        - 2.0
  - name: duration  # Just for testing
    fixed_value: 40

policy:
  model: "ProfitMaximizingPolicy"
loss:
  model: "LossModel"
  alpha: 10
  target_speed: *target_speed
  beta: 1
  scale: 0.1
preference_prior:
  model: "ExponentialPreferencePrior"
  p_star: 0.5
risk:
  model: "MonteCarloRiskModel"
