# Special hydra param, inherit defaults
defaults:
  - _self_

# Overrides for the env config
# See AVHighway for defaults
highway_env:
  controlled_vehicles: &n_controlled 8  # Number of ego vehicles
  control_vehicle_type: "sim.vehicles.highway.IDMVehicle"
  vehicles_count: 30  # Number of alters
  vehicles_density: 2
  reward_speed: 42
  speed_limit: 40
  action:
    type: "MultiAgentAction"
    action_config:
      type: "DiscreteMetaAction"
      lateral: true
      longitudinal: true
  observation:
    type: "MultiAgentObservation"
    observation_config:
      type: "Kinematics"
#      features: ["presence", "x", "y", "vx", "vy"]
  mc_horizon: &mc_horizon 20
  n_montecarlo: &n_montecarlo 100
  duration: 400
  normalize_reward: true
#==============
name: multiagent
seed: 867
world_draws: 1
warmup_steps: 1e5  # included within the duration
mc_period: &mc_period 2   # real-world steps between MC issuances

# Multiprocessing configs
use_mp: false
multiprocessing_cpus: 8


gatekeeper:
  n_controlled: *n_controlled
  mc_period: *mc_period
  # Montecarlo params
  mc_horizon: *mc_horizon
  n_montecarlo: *n_montecarlo
  # Models
  preference_prior:
    model: "ExponentialPreferencePrior"
    p_star: 0.1
    l_star: 0.9
  risk_model:
    model: "DifferentialEntropyRiskModel"
    threshold: -5.0
