# Special hydra param, inherit defaults
defaults:
  - _self_

# Overrides for the env config
# See AVHighway for defaults
highway_env:
  controlled_vehicles: 4  # Number of ego vehicles
  vehicles_count: 20  # Number of alters
  vehicles_density: 2
  target_speed: 40
  speed_limit: 40
  action:
    type: "MultiAgentAction"
    action_config:
      type: "DiscreteMetaAction"
      lateral: false
      longitudinal: true
#      meta_actions: ["LANE_LEFT", "IDLE", "LANE_RIGHT", "FASTER", "SLOWER"]
  observation:
    type: "MultiAgentObservation"
    observation_config:
      type: "Kinematics"
#      features: ["presence", "x", "y", "vx", "vy"]
  mc_horizon: 3
  n_montecarlo: 5
  duration: 100
#==============
name: multiagent
seed: 867
world_draws: 1
warmup_steps: 10000  # included within the duration
mc_period: 2  # real-world steps between MC issuances

preference_prior:
  model: "ExponentialPreferencePrior"
  p_star: 0.5
  l_star: 0.1
risk:
  model: "DifferentialEntropyRiskModel"
