# Special hydra param, inherit defaults
defaults:
  - _self_

# Overrides for the env config
# See AVHighway for defaults
highway_env:
  controlled_vehicles: &n_controlled 1  # Number of ego vehicles
  control_vehicle_type: "sim.vehicles.highway.IDMVehicle"
  vehicles_count: 24  # Number of alters
  vehicles_density: 1
  reward_speed: 30
  speed_limit: 30
  action:
    type: "MultiAgentAction"
    action_config:
      type: "DiscreteMetaAction"
      lateral: true
      longitudinal: true
  observation:
    type: "MultiAgentObservation"
    observation_config:
      type: "Kinematics"
#      features: ["presence", "x", "y", "vx", "vy"]
  mc_horizon: 20
  n_montecarlo: 40
  duration: 200
  normalize_reward: true
#==============
name: tracker
seed: 867
world_draws: 1
warmup_steps: 0  # included within the duration
mc_period: 20  # real-world steps between MC issuances

# Multiprocessing configs
use_mp: false
multiprocessing_cpus: 2

preference_prior:
  model: "ExponentialPreferencePrior"
  p_star: 0.1
  l_star: 0.9
risk:
  model: "PreferenceDivergenceRiskModel"
