# Special hydra param, inherit defaults
defaults:
  - _self_

# Overrides for the env config
# See AVHighway for defaults
env:
  vehicles_count: 30
  vehicles_density: 2
  target_speed: &target_speed 40
  speed_limit: 40
  mc_horizon: 15
  n_montecarlo: 20
  duration: 500
#  mc_period: 5
#==============
seed: 867
world_draws: 1
warmup_steps: 20  # included within the duration

preference_prior:
  model: "SoftmaxPreferencePrior"
  kappa: 1.0
risk:
  model: "DifferentialEntropyRiskModel"
