# Special hydra param, inherit defaults
defaults:
  - _self_

# Note this can still be overridden with 'name' in the command line
name: tmp/highway
run_dir: ../results/${name}

hydra:
  run:
    dir: ${run_dir}
  # Format the logging so that it overwrites instead of appending
  job_logging:
    handlers:
      file:
        filename: ${run_dir}/out.log
        mode: w

# See AVHighway for defaults
highway_env:
  control_vehicle_type: "sim.vehicles.highway.IDMVehicle"
  other_vehicles_type: "sim.vehicles.highway.AlterIDMVehicle"
  default_control_behavior: "sim.vehicles.highway.HotshotParams"
  # Vehicle numbers
  controlled_vehicles: 12  # Number of ego vehicles
  vehicles_count: 24
  # Number of vehicles with the reward_speed target
  # Remainder will have a target speed lower than speed_limit
  num_vehicles_control_speed: 12

  vehicles_density: 1.
  reward_speed: 40
  speed_limit: 20
  action:
    type: "MultiAgentAction"
    action_config:
      type: "DiscreteMetaAction"
      lateral: true
      longitudinal: true
  observation:
    type: "MultiAgentObservation"
    observation_config:
      type: "Kinematics"
#      features: ["presence", "x", "y", "vx", "vy"]
  mc_horizon: 1
  n_montecarlo: 20
  duration: 100
  normalize_reward: true
#==============

seed: 867
world_draws: 40
warmup_steps: 1e5  # included within the duration
mc_period: 5   # real-world steps between MC issuances
num_collision_watch: 4 # Watch the first n vehicles for terminating collision

# Temporary, probably will remove
env_type: "highway-v0"

# Multiprocessing configs
multiprocessing_cpus: 12
# Note that you'll be using an additional CPU for each world parent (but they're low usage)
cores_per_world: 4
# Profiling
profiling: false
video: false

gatekeeper:
  # Number of vehicles that will have gatekeeper behavior operating on
  n_online: 12
  # Time-discounting
  enable_time_discounting: false
  gamma: 0.96
  risk_eval_period: 5  # Every nth inner step, eval risk
  # Models
  preference_prior:
    model: "ExponentialPreferencePrior"
    p_star: 0.1
    l_star: 0.2
  risk_model:
    model: "NullEntropyRiskModel"
  behavior_cfg:
    enable: true
    policy_change_delta: 10
    # The GK policy for how vehicle behavior modes are selected
    control_policy: "risk_threshold"
    nominal_class: "sim.vehicles.highway.HotshotParams"
    defensive_class: "sim.vehicles.highway.DefensiveParams"
    offline_class: "sim.vehicles.highway.HotshotParams"
