# Special hydra param, inherit defaults
defaults:
  - _self_

# Overrides for the env config
# See AVHighway for defaults
highway_env:
  controlled_vehicles: 1  # Number of ego vehicles
  control_vehicle_type: "sim.vehicles.highway.IDMVehicle"
  other_vehicles_type: "sim.vehicles.highway.AlterIDMVehicle"
  vehicles_count: 24  # Number of alters
  vehicles_density: 2
  reward_speed: 40
  speed_limit: 40
  action:
    type: "MultiAgentAction"
    action_config:
      type: "DiscreteMetaAction"
      lateral: true
      longitudinal: true
  observation:
    type: "MultiAgentObservation"
    observation_config:
      type: "Kinematics"
#      features: ["presence", "x", "y", "vx", "vy"]
  mc_horizon: 20
  n_montecarlo: 20
  duration: 200
  normalize_reward: true
#==============

name: ttc
seed: 86777
world_draws: 200
warmup_steps: 0  # included within the duration
mc_period: 10   # real-world steps between MC issuances

# Multiprocessing configs
use_mp: true
multiprocessing_cpus: 8

gatekeeper:
  # Time-discounting
  enable_time_discounting: false
  gamma: 0.96
  risk_eval_period: 5  # Every nth inner step, eval risk
  # Models
  preference_prior:
    model: "ExponentialPreferencePrior"
    p_star: 0.1
    l_star: 0.2
  risk_model:
    model: "NullEntropyRiskModel"
  behavior_cfg:
    enable: true
    nominal_class: "sim.vehicles.highway.AggressiveParams"
    conservative_class: "sim.vehicles.highway.ConservativeParams"
