observation:
  type: Kinematics
action:
  type: DiscreteMetaAction
duration: 40
centering_position:
  - 0.3
  - 0.5
collision_reward: -1
controlled_vehicles: 1
vehicles_count: 50
vehicles_density: 1
ego_spacing: 2
high_speed_reward: 0.4
initial_lane_id: null
lane_change_reward: 0
lanes_count: 6
manual_control: false
normalize_reward: true
offroad_terminal: false
offscreen_rendering: true
other_vehicles_type: highway_env.vehicle.behavior.IDMVehicle
policy_frequency: 1
real_time_rendering: false
render_agent: true
reward_speed_range:
  - 20
  - 30
right_lane_reward: 0.1
scaling: 5.5
screen_height: 150
screen_width: 600
show_trajectories: false
simulation_frequency: 15
